import Button from "@/components/Button";
import Head from "next/head";
import React from "react";

export default function About() {
    const onClickEventHandler = () => {
        alert('onClickEventHandler called');
    }
  return (
    <>
      <Head>
        <title>About Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Button onClickEvent={onClickEventHandler} shades="primary" label='Prev' />
        <Button onClickEvent={onClickEventHandler} shades="secondary"  label='Next' />
        <Button onClickEvent={onClickEventHandler} />

      </div>
    </>
  );
}
